// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Yf5kf4liUyTCZxFKyAjn4ddLlwpLi6Y',
    appId: '1:581128416323:web:eba4f8c7c4794e1310f8f6',
    messagingSenderId: '581128416323',
    projectId: 'sahay-a312b',
    authDomain: 'sahay-a312b.firebaseapp.com',
    storageBucket: 'sahay-a312b.firebasestorage.app',
    measurementId: 'G-7Z8CE9MCK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGW6GoO1IE3fhI4rf2WwDu0TyqXMJt6EQ',
    appId: '1:581128416323:android:6d15570ba9275f1e10f8f6',
    messagingSenderId: '581128416323',
    projectId: 'sahay-a312b',
    storageBucket: 'sahay-a312b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbN85Z9_HHvUtwInE8905TMJhDE6uzJOI',
    appId: '1:992789459549:ios:5a558fce0f720b6cf793b4',
    messagingSenderId: '992789459549',
    projectId: 'nari-shakti-hacksagon',
    databaseURL: 'https://nari-shakti-hacksagon-default-rtdb.firebaseio.com',
    storageBucket: 'nari-shakti-hacksagon.firebasestorage.app',
    iosBundleId: 'com.example.nariShakti',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbN85Z9_HHvUtwInE8905TMJhDE6uzJOI',
    appId: '1:992789459549:ios:5a558fce0f720b6cf793b4',
    messagingSenderId: '992789459549',
    projectId: 'nari-shakti-hacksagon',
    databaseURL: 'https://nari-shakti-hacksagon-default-rtdb.firebaseio.com',
    storageBucket: 'nari-shakti-hacksagon.firebasestorage.app',
    iosBundleId: 'com.example.nariShakti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Yf5kf4liUyTCZxFKyAjn4ddLlwpLi6Y',
    appId: '1:581128416323:web:eba4f8c7c4794e1310f8f6',
    messagingSenderId: '581128416323',
    projectId: 'sahay-a312b',
    authDomain: 'sahay-a312b.firebaseapp.com',
    storageBucket: 'sahay-a312b.firebasestorage.app',
    measurementId: 'G-7Z8CE9MCK8',
  );
}
