// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm6pp8C-3g4ChAoozTvbVKXSncy6jtNaI',
    appId: '1:992789459549:web:7e40ed9c7c790aa2f793b4',
    messagingSenderId: '992789459549',
    projectId: 'nari-shakti-hacksagon',
    authDomain: 'nari-shakti-hacksagon.firebaseapp.com',
    storageBucket: 'nari-shakti-hacksagon.firebasestorage.app',
    measurementId: 'G-EPZ7PEN2HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9mTTfVebQDcrEfPHOc1gFUlf9ED6Jpm4',
    appId: '1:992789459549:android:e704ee14c9bb53a6f793b4',
    messagingSenderId: '992789459549',
    projectId: 'nari-shakti-hacksagon',
    storageBucket: 'nari-shakti-hacksagon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbN85Z9_HHvUtwInE8905TMJhDE6uzJOI',
    appId: '1:992789459549:ios:5a558fce0f720b6cf793b4',
    messagingSenderId: '992789459549',
    projectId: 'nari-shakti-hacksagon',
    storageBucket: 'nari-shakti-hacksagon.firebasestorage.app',
    iosBundleId: 'com.example.nariShakti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbN85Z9_HHvUtwInE8905TMJhDE6uzJOI',
    appId: '1:992789459549:ios:5a558fce0f720b6cf793b4',
    messagingSenderId: '992789459549',
    projectId: 'nari-shakti-hacksagon',
    storageBucket: 'nari-shakti-hacksagon.firebasestorage.app',
    iosBundleId: 'com.example.nariShakti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm6pp8C-3g4ChAoozTvbVKXSncy6jtNaI',
    appId: '1:992789459549:web:fcaae4e68f980bd2f793b4',
    messagingSenderId: '992789459549',
    projectId: 'nari-shakti-hacksagon',
    authDomain: 'nari-shakti-hacksagon.firebaseapp.com',
    storageBucket: 'nari-shakti-hacksagon.firebasestorage.app',
    measurementId: 'G-DLHTWFRD9J',
  );
}
